### PR TITLE
Refine `cref` handling

### LINKED ISSUE #30: File names are not fully qualified
Currently, file names are not fully qualified, so potentially there could be a name collision.

Instead, we should use fully qualified names in file names. Also, for generics we should use the same names, but formatted with `<>` brackets as headers.

### LINKED ISSUE #44: Incorrect `<see cref="...">` link in rendered Markdown
The generated documentation creates a link to non-existent docs for `<see cref="...">` references to methods.

image

https://github.com/candy-kingdom/summary/blob/master/docs/Sample%7BT0%2CT1%7D.md#methodm0-m1-m2short-string

### PR DESCRIPTION
**Pull request by joshua-light**
Previously, we handled `cref` only partially.

In this PR, a few improvements and fixes are introduced:
- Now almost all `<see cref="...">` are handled properly
- `<inheritdoc>` also works properly
- References to fields, methods, etc. are properly handled via HTML `#...` syntax
- References that we can't resolve are now rendered as dummy links (simple underscored text).

Improvements to do:
- Handle standard types.

Closes #44. Closes #30.

### CODE REVIEW

File: src/Core/Caching/CrefCache.cs [hunk 1]
```diff
@@ -0,0 +1,82 @@
...
+            : RawCrefs[self] = RawCrefRegex().Replace(self.AsCref(), "");
+
+    [GeneratedRegex(@"(?<={)[^{},]*(?=,)|(?<=,)[^{},]*(?=})")]
+    private static partial Regex RawCrefRegex();
+
+    /// <summary>
+    ///     Converts the given string from the format of <c>cref</c> attribute value.
+    /// </summary>
+    /// <example>
+    ///     In the following example, the <c>"Some&lt;T1, T2&gt;"</c> string
```
Comment (joshua-light) [inline src/Core/Caching/CrefCache.cs]: Typo
